### PR TITLE
CI: add markdown link check action

### PR DESCRIPTION
**Pull request by qaristote**
This PR implements the feature proposed in #25.

### CODE REVIEW

**Comment by qaristote** [comment]
It seems the test doesn't manage to find the `README.md` file somehow ...

**Review by facundominguez — APPROVED** [review]
LGTM

**Comment by facundominguez** [comment]
hm, the output is not very telling but the linter is run on some file, or otherwise no output would be produced.

Maybe more verbosity can be enabled, or perhaps this could be tested by breaking  some link in the README.

**Comment by qaristote** [comment]
#29 is broken so we're all good.

**Pull request merged**
